# Generated by Django 5.1.3 on 2025-02-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mascotas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascota",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
