# Generated by Django 5.1.3 on 2025-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mascotas", "0002_alter_mascota_fecha_nacimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="imagen",
            field=models.TextField(null=True),
        ),
    ]
