# Generated by Django 5.1.3 on 2025-02-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mascotas", "0003_mascota_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="dueño",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
    ]
